blog_pro/blog/app_login/urls.py
from django.urls import path
from . import views

app_name = 'app_login'

urlpatterns = [
    path('signup/', views.Signup, name='signup'),
    path('login/', views.Login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.Profile, name='profile'),
    path('user_change/', views.user_change, name='user_change'),
    path('password/', views.pass_change, name='pass_change'),
    path('add-picture/', views.add_pro_pic, name='add_pro_pic'),
    path('change-picture/', views.change_pro_pic, name='change_pro_pic'),
]

blog_pro/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('app_blog.urls')),
    path('blog/', include('app_login.urls')),
    path('', views.index, name='index'),
]

urlpatterns +=staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_pro/blog/app_login/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='pro_pic')


blog_pro/blog/app_login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import UserProfile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="Email Address", required=True)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password')

class ProfilePic(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_pic',)


blog_pro/blog/app_login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login, authenticate, logout
from django.urls import reverse
from django.shortcuts import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .forms import SignUpForm, UserProfileChange, ProfilePic

# Create your views here.
def Signup(request):
    form = SignUpForm()
    registered = False
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True
    dict = {'form': form, 'registered': registered}
    return render(request, 'app_login/signup.html', context=dict)

def Login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
    return render(request, 'app_login/login.html', context={'form': form})

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def Profile(request):
    return render(request, 'app_login/profile.html', context={})

@login_required
def user_change(request):
    current_user = request.user
    form = UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user)
    return render(request, 'app_login/change_profile.html', context={'form': form})

@login_required
def pass_change(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
    return render(request, 'App_Login/pass_change.html', context={'form':form, 'changed': changed})


@login_required
def add_pro_pic(request):
    form = ProfilePic()
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('app_login:profile'))
    return render(request, 'app_login/pro_pic_add.html', context={'form': form})

@login_required
def change_pro_pic(request):
    form = ProfilePic(instance=request.user.user_profile)
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('app_login:profile'))
    return render(request, 'app_login/pro_pic_add.html', context={'form': form})

blog_pro/blog/templates/app_login/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Login {% endblock %}

{% block body %}
<div class="container">
<form method="POST">
  {{ form|crispy }}
  {% csrf_token %}
  <button type="submit" class="btn btn-warning btn-sm">Change</button>
</form>
</div>
{% endblock %}

blog_pro/blog/templates/app_login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Login {% endblock %}

{% block body %}
<div class="container">
    <h2 style="color:red;">Login:</h2>
    <form method="POST">
    {{ form|crispy }}
    {% csrf_token %}

    <button type="submit" class="btn btn-success btn-sm">login</button>
    </form>

    <br>
<p>Not have an account? <a href="{% url 'app_login:signup' %}">Register Here</a></p>
</div>

{% endblock %}

blog_pro/blog/templates/app_login/pass_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Change Pass {% endblock %}
{% block body %}

{% if changed %}
<div class="alert alert-success">
  Password Change Successfully!
</div>
{% endif %}
<form method="POST">
  {{ form|crispy }}
  {% csrf_token %}
  <button type="submit" class="btn btn-warning btn-sm">Change</button>
</form>
{% endblock %}

blog_pro/blog/templates/app_login/pro_pic_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Profile {% endblock %}
{% block body %}

<h2>Add Your Profile Picture:</h2>
<form method="POST" enctype="multipart/form-data">
  {{form|crispy}}
  {% csrf_token %}
  <button type="submit" class="btn btn-success btn-sm">Add</button>
</form>
{% endblock %}

blog_pro/blog/templates/app_login/profile.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
    <h2 style="color:purple;">Your Profile:</h2>
    <hr>
{% if user.user_profile.profile_pic %}
    <img src="/media/{{user.user_profile.profile_pic}}" class="rounded-circle" width="140px">
    <br>
    <a href="{% url 'app_login:change_pro_pic' %}" class="btn btn-info btn-sm">Change Profile Picture</a>


{% else %}
    <img src="/media/pro_pic/avator.jpg" class="rounded-circle" width="140px">
    <br>
    <br>
    <a href="{% url 'app_login:add_pro_pic' %}" class="btn btn-info btn-sm">Change Profile Picture</a>

{% endif %}
    <br>
    <p>Username: {{user.username}} </p>
    <p>Email: {{user.email}} </p>
    <p>Name: {{user.first_name}} {{user.last_name}}</p>

    <br>
<a href="{% url 'app_login:user_change' %}" class="btn btn-warning btn-sm">Change Profile Info</a>
</div>

{% endblock %}

blog_pro/blog/templates/app_login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} SignUp {% endblock %}

{% block body %}

{% if registered %}
<div class="alert alert-success">
  Account Created Successfully! <a href="#">Login Here</a>
</div>

{% else %}


<div class="container">
    <h2 style="color:red;">Create New Account:</h2>
    <form method="POST">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">Create Account</button>
    </form>

    <br>
<p>Already have an account? <a href="{% url 'app_login:login' %}">Login Here</a></p>
</div>


{% endif %}

{% endblock %}