blog_pro/blog/app_blog/urls.py
from django.urls import path
from . import views

app_name = 'app_blog'

urlpatterns =[
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<str:slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('my-blogs/', views.MyBlogs.as_view(), name='my_blogs'),
    path('edit/<pk>/', views.UpdateBlog.as_view(), name='edit_blog'),


]

blog_pro/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('app_blog.urls')),
    path('blog/', include('app_login.urls')),
    path('', views.index, name='index'),
]

urlpatterns +=staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_pro/blog/app_blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.

class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=250, verbose_name="Put a Title")
    slug = models.SlugField(max_length=250, unique=True,allow_unicode=True)
    blog_content = models.TextField(verbose_name="what is on your mind")
    blog_image = models.ImageField(upload_to='blog_images', verbose_name="Image")
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-publish_date',)

    def __str__(self):
        return self.blog_title

    def _generate_unique_slug(self):
        unique_slug = slugify(self.blog_title,allow_unicode=True)
        num = 1
        while Blog.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(unique_slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._generate_unique_slug()
        super().save(*args, **kwargs)


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-comment_date',)
    def __str__(self):
        return self.comment

class Likes(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='liked_blog')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="liked_user")

    def __str__(self):
        return self.user + "likes" + self.blog


blog_pro/blog/app_blog/forms.py
from django import forms
from .models import Blog, Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

blog_pro/blog/app_blog/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.http import HttpResponse
from django.views.generic import CreateView, UpdateView, ListView, DeleteView, View, TemplateView
from .models import Likes, Blog, Comment
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CommentForm
import uuid

# Create your views here.
class MyBlogs(LoginRequiredMixin, TemplateView):
    template_name = 'app_blog/my_blogs.html'

class CreateBlog(LoginRequiredMixin, CreateView):
    model = Blog
    template_name = 'app_blog/create_blog.html'
    fields = ('blog_title', 'blog_content', 'blog_image',)

    def form_valid(self, form):
        blog_obj = form.save(commit=False)
        blog_obj.author = self.request.user
        blog_obj.save()
        return HttpResponseRedirect(reverse('index'))

class BlogList(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'app_blog/blog_list.html'
    #queryset = Blog.objects.order_by('-publish_date')

@login_required
def blog_details(request, slug):
    blog = Blog.objects.get(slug=slug)
    comment_form = CommentForm()
    already_liked = Likes.objects.filter(blog=blog, user=request.user)
    if already_liked:
        liked = True
    else:
        liked = False
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.blog = blog
            comment.save()
            return HttpResponseRedirect(reverse('app_blog:blog_details', kwargs={'slug': slug}))
    return render(request, 'app_blog/blog_details.html', context={'blog': blog, 'comment_form': comment_form, 'liked': liked,})

@login_required
def liked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    if not already_liked:
        liked_post = Likes(blog=blog, user=user)
        liked_post.save()
    return HttpResponseRedirect(reverse('app_blog:blog_details', kwargs={'slug': blog.slug}))

@login_required
def unliked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('app_blog:blog_details', kwargs={'slug': blog.slug}))

class UpdateBlog(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('blog_title', 'blog_content', 'blog_image')
    template_name = 'app_blog/edit_blog.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('app_blog:blog_details', kwargs={'slug': self.object.slug})



blog_pro/blog/templates/app_blog/blog_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock %}
{% block body %}

<div class="container">
<div class="row">
    <div class="col-sm-6">
        <h2>{{blog.blog_title}}</h2>
        <h4>Posted By:@{{blog.author}}</h4>
        <h6><i>Published On:{{blog.publish_date}}</i></h6>
        <h6><i>Update On: {{blog.update_date}}</i></h6>
        <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count}}  Comments</h6>
    </div>

    <div class="col-sm-6">
        <img src="/media/{{blog.blog_image}}" width="100%">
    </div>
    <p>{{blog.blog_content|linebreaks}}</p>
    <hr>
</div>


{% if not liked %}
  <a href="{% url 'app_blog:liked_post' pk=blog.pk %}">
    <i class="fa fa-thumbs-o-up fa-2x" aria-hidden="true"></i>
  </a>
  {% else %}
  <a href="{% url 'app_blog:unliked_post' pk=blog.pk %}">
    <i class="fa fa-thumbs-o-down fa-2x" aria-hidden="true"></i>
  </a>
  {% endif %}


<div class="row">
<div class="col-sm-6">
    <hr>
    <h4>Comments:</h4>
    {% for comment in blog.blog_comment.all %}
    <p><a href="">@{{comment.user}}</a>
        {{comment.comment}}<br><h6>{{comment.comment_date}}</h6></p>
    {% endfor %}
</div>
    <div class="col-sm-6">
        <form method="POST">
            {{comment_form|crispy}}
            {% csrf_token %}
            <input type="submit" class="btn btn-info " value="Comment">
        </form>
    </div>

</div>
</div>
{% endblock %}

blog_pro/blog/templates/app_blog/blog_list.html
{% extends 'base.html' %}
{% load custom_filter %}
{% block body %}

<div class="container">
{% for blog in blogs %}
<h3>{{blog.blog_title}}</h3>
<h6><i>{{blog.publish_date}}</i></h6>

<div class="row">

  <div class="col-sm-8">
    <p>{{blog.blog_content|range_filter|linebreaks}} <a href="{% url 'app_blog:blog_details' slug=blog.slug %}">Read More</a></p>
    <h6>Posted By: <a href="#">@{{blog.author}}</a></h6>
    <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count }}  Comments </h6>
  </div>

  <div class="col-sm-4">
    <img src="/media/{{blog.blog_image}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width="100%">
  </div>

</div>
<hr>
{% endfor %}
  </div>

{% endblock %}

blog_pro/blog/templates/app_blog/create_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  {{ form|crispy }}
  {% csrf_token %}
  <button type="submit" class="btn btn-success btn-sm">Publish</button>
</form>

{% endblock %}

blog_pro/blog/templates/app_blog/edit_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock %}

{% block body %}

{% if blog.author == user %}
    <form method="POST">
    {{form|crispy}}
    {% csrf_token %}
    <button type="submit" name="button">Update</button>
    {% else %}
    <p>Your are not allowed to view this page. 404</p>
    </form>
{% endif %}

{% endblock %}

blog_pro/blog/templates/app_blog/my_blogs.html
{% extends 'base.html' %}
{% load custom_filter %}

{% block title_block %} {{blog.blog_title}} {% endblock %}
{% block body %}

{% for blog in user.post_author.all %}
<h3>{{blog.blog_title}}</h3>
<h6>{{blog.publish_date}}</h6>
<div class="row">
  <div class="col-sm-4">
    <img src="/media/{{blog.blog_image}}" width="100%">
  </div>
  <div class="col-sm-8">
    <p>{{blog.blog_content|range_filter|linebreaks}}</p>
    <a href="{% url 'app_blog:blog_details' slug=blog.slug %}">Read More</a>
  </div>
</div>
<a href="{% url 'app_blog:edit_blog' pk=blog.pk %}">Edit</a>
<hr>
{% endfor %}

{% endblock %}